# Generated by Django 5.2.6 on 2025-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('place_type', models.CharField(choices=[('restaurant', 'Ресторан'), ('cafe', 'Кафе'), ('park', 'Парк'), ('cinema', 'Кінотеатр'), ('museum', 'Музей'), ('other', 'Інше')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
