# Generated by Django 5.2.6 on 2025-09-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='places/default.jpg', upload_to='places/'),
        ),
    ]
